if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'junegunn/goyo.vim'
"Plug 'reedes/vim-pencil'
call plug#end()

"====== Interface ======
"set mouse=i
set linebreak
set wrap
set spelllang=en_us
set smarttab
set showcmd
set conceallevel=3
set scrolloff=2
set laststatus=2
set showtabline=2
cabbrev help tab help
set hidden
set noshowmode
set incsearch
syntax on
"====== spaces ======
set listchars=trail:◦,tab:▸-,nbsp:+
"====== Hightlight ======
hi clear SpellBad
hi SpellBad term=NONE ctermbg=NONE cterm=underline
hi clear SpellCap
hi SpellCap term=NONE ctermbg=NONE cterm=NONE
"====== leader ======
nnoremap <leader>f :<C-U>RangerChooser<CR>
nnoremap <leader>b :buffers!<CR>
"====== netrw ======
let g:netrw_liststyle = 3
let g:netrw_banner = 0
" ====== plugs ======
so ~/.vim/plugs.vim
let g:airline_theme = 'papercolor'
