# wallpaper
# sh ~/.fehbg &
compton -b &
## Note to self, keys: no mod, shift, switch
# map delete to eject
xmodmap -e "keycode 169 = Delete NoSymbol Delete" &
# caps_lock = modeswitch
xmodmap -e "keycode 66 = Mode_switch Caps_Lock"
# caps+arrows
xmodmap -e "keycode 113 = Left NoSymbol Home"
xmodmap -e "keycode 114 = Right NoSymbol End"
xmodmap -e "keycode 111 = Up NoSymbol Prior"
xmodmap -e "keycode 116 = Down NoSymbol Next"
# startx
exec i3 
