#!/bin/bash
set -e

    echo
    tput setaf 3
    . /home/sir/py3.env/bin/activate && echo "(py3.env)"
    tput sgr 0
while true
do
    echo "  create a post?"
    read -r play
        if [[ $play == "no" ]] ; then
            deactivate && echo "py3.env: deactivated"
            tput setaf 4
            echo "Until next time."
            tput sgr 0
            exit 0

        elif [[ $play == "yes" ]] ; then
            post=/home/sir/rmf/active
            cat /home/sir/rmf/header > $post

                while : ; do
                    echo "  written by:"
                    read -r bit

                    cat /home/sir/rmf/posted | egrep -wi --color "${bit,,}" || echo "..."
                    unset repeat
                    until [[ $repeat == @(yes|no) ]] ; do

                    echo "   been posted?"
                    read -r repeat
                done
                if [[ $repeat == "no" ]] ; then
                    tput setaf 2
                    echo "let's get this post started."
                    tput sgr 0
                        read -rp "  was that they full name? " bit2
                            if [[ $bit2 == "yes" ]]; then
                                author=$bit
                            else
                                read -a author -rp "  well? "
                                author=${author[@]}
                            fi
                break
                fi
                done
                       
            echo "  okay, so $author wrote..." 
            read -a title
            title=${title[@]}
            echo "  and the summary:"
            read -a summary
            summary=${summary[@]}

            read -rp "  [a]o3, [f]fn, [p]&p, [l]j? " www
                if [[ $www == "a" ]] ; then
                    read -rp "  ao3 id? " aid
                    link=http://archiveofourown.org/works/$aid
                    site=ao3
                elif [[ $www == "f" ]] ; then
                    read -rp "  ffn id? " fid
                    link=http://www.fanfiction.net/s/$fid
                    site=ffn
                elif [[ $www == "p" ]] ; then 
                    read -rp "  link? " link  
                    site=p&p
                    link=$link
                elif [[ $www == "l" ]] ; then
                    read -rp "  link? " link
                    site=lj
                    link=$link
                fi
    
            read -rp "  chapters q) 1-2, m) 3-9, l) 10-20, n) 21+, u) wip? " sandl
                if [[ $sandl == "u" ]] ; then
                    status=wip
                    length=""
                elif [[ $sandl == "q" ]] ; then
                    status=complete
                    length=quickie
                elif [[ $sandl == "m" ]] ; then
                    status=complete
                    length=medium
                elif [[ $sandl == "l" ]] ; then
                    status=complete
                    length=medium
                elif [[ $sandl == "n" ]] ; then
                    status=complete
                    length=novel
                fi
    
            read -rp " series? " after
                if [[ $after == "no" ]] ; then
                    echo "client.create_text('randommirandyfics', state=\"queue\", format=\"markdown\", tags=[\"mirandy\", \""$title"\", \""$author"\", \""$site"\", \""$status"\", \""$length"\"], title=\"$summary\", body=\"[$title]($link) by $author\")" >> $post
                elif [[ $after == "yes" ]] ; then
                    read -a title2 -rp "  follows..."
                    title2=${title2[@]}
                    read -rp "  link?" link2
                    echo "client.create_text('randommirandyfics', state=\"queue\", format=\"markdown\", tags=[\"mirandy\", \""$title"\", \""$author"\", \""$site"\", \""$status"\", \""$site"\"], title=\"$summary\", body=\"[$title]($link) by $author Folloqs [$after]($link2)\")" >> $post
                fi
    
            vim -c :Goyo $post
            echo "..."
        
            read -rp " post it? " queue
                if [[ $queue == "no" ]] ; then
                    tput setaf 8
                    echo "okay, post saved"
                    cp $post /home/sir/rmf/saved
                    tput sgr 0
                elif [[ $queue == "yes" ]] ; then
                    python $post
                    echo "${title,,} -- ${author,,}" >> /home/sir/rmf/posted
                    tput setaf 2
                    echo " it is done."
                    tput sgr 0
                    echo
                fi
        continue
        fi
done
