#!/bin/bash -e
# varibles
dmail=dropbox:writer/email
# start
cd $HOME/.config/
cp -t $HOME/.dotfiles/config -rv compton.conf dunst/ i3/ neofetch/ polybar/ termite/ user-dirs.dirs
cp user-dirs.dirs $HOME/.dotfiles/writer/
cd $HOME/.config/ranger
cp -t $HOME/.dotfiles/config/ranger/ -v devicons.py rc.conf rifle.conf scope.sh
cd $HOME/.config/qutebrowser
cp -t $HOME/.dotfiles/qutebrowser -v keys.conf qutebrowser.conf 
echo "rclone sync"
rclone sync quickmarks dropbox:writer/
cd $HOME
cp -v .gmrunrc $HOME/.dotfiles/gmrunrc
cp -v .fehbg $HOME/.dotfiles/fehbg
cp .vim/more.vim $HOME/.dotfiles/
echo "more rclone"
rclone sync .vim/brev.vim dropbox:writer/
echo "..."
rclone sync .mutt/ $dmail/mutt
rclone sync .notmuch-config $dmail
echo "..."
rclone sync .offlineimaprc $dmail
rclone sync .msmtprc $dmail
echo "rclone stuff done"
cp -v rmf/posted $HOME/.dotfiles/rmf-posted
cp -v .sdcv_ordering $HOME/.dotfiles/sdcv_ordering
cp -v .vimrc $HOME/.dotfiles/vimrc
cp -v .xinitrc $HOME/.dotfiles/writer/xinitrc
cp -v .zprofile $HOME/.dotfiles/writer/zprofile
cd $HOME/.zsh
cp -t $HOME/.dotfiles/writer/zsh/ -v alias history.zsh other
cp $HOME/.zshrc $HOME/.dotfiles/writer/zshrc
