#!/bin/bash
# xmod key reassignments (key, shift, switch) 
# make eject delete
xmodmap -e "keycode 169 = Delete NoSymbol Delete"
# make caps lock be mode switch
xmodmap -e "keycode 66 = Mode_switch"
# make mode switch and arrows do fun
xmodmap -e "keycode 113 = Left NoSymbol Home"
xmodmap -e "keycode 114 = Right NoSymbol End"
xmodmap -e "keycode 111 = Up NoSymbol Prior"
xmodmap -e "keycode 116 = Down NoSymbol Next"


